import QueryProvider from "@/component/QueryProvider";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Face Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
        <head>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap');
</style>
      </head>
      <body>
        <QueryProvider>
        {children}
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
