import Navbar from "../component/Navbar";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Face Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
